title: X3LF
description: "Какие-то новости"
author:
  name: "X3LF"
  email: "x3lf@protonmail.com"
  url: "https://x3lf.github.io/school"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "X3LR"
year : "2019"
